#:schema node_modules/wrangler/config-schema.json
name = "c3-scheduled"
main = "src/index.ts"
compatibility_date = "2024-10-11"

[triggers]
# Run on December 31st at midnight UTC
crons = ["0 0 31 12 *"]

[observability]
enabled = true
